export const  ADD_INGREDIENT = 'ADD_INGREDIENT';
export const  REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const  SET_INGREDIENTS = 'SET_INGREDIENTS';
export const  SET_HAS_ERRORS = 'SET_HAS_ERRORS';

export const  ORDER_BURGER_INIT = 'ORDER_BURGER_INIT';
export const  ORDER_BURGER_START = 'ORDER_BURGER_START';
export const  ORDER_BURGER_SUCCESS = 'ORDER_BURGER_SUCCESS';
export const  ORDER_BURGER_FAIL = 'ORDER_BURGER_FAIL';

export const  FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const  FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const  FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const  AUTH_START = 'AUTH_START';
export const  AUTH_SUCCESS = 'AUTH_SUCCESS';
export const  AUTH_FAIL = 'AUTH_FAIL';
export const  AUTH_LOGOUT = 'AUTH_LOGOUT';
